Fix calendar and date picker errors
Fixes the following errors:
- src/components/ui/calendar.tsx(56,9): error TS2353: Object literal may only specify known properties, and 'IconLeft' does not exist in type 'Partial<CustomComponents>'.
- src/components/ui/date-picker.tsx(39,11): error TS2322: Type '{ mode: "single"; selected: Date; onSelect: (date: Date) => void; initialFocus: true; locale: Locale; }' is not assignable to type 'IntrinsicAttributes & DayPickerProps'.